slr_label/slr/models.py
from slr_label import db

assignments = db.Table('assignment',
    db.Column('paper_id', db.Integer, db.ForeignKey('paper.id'), primary_key=True),
    db.Column('user_id', db.Integer, db.ForeignKey('user.id'), primary_key=True)
)


class Question(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    question = db.Column(db.String, nullable=False)
    type = db.Column(db.Integer, nullable=False)

    def __str__(self):
        return self.question


class Paper(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String, nullable=False)
    authors = db.Column(db.String)
    venue = db.Column(db.String)
    doi = db.Column(db.String)
    labelers = db.relationship('User', secondary=assignments, lazy='subquery',
                               backref=db.backref('papers', lazy=True, order_by=id))

    def __str__(self):
        return self.title


class NewPaper(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String, nullable=False)
    authors = db.Column(db.String)
    venue = db.Column(db.String)
    doi = db.Column(db.String)
    paper_id = db.Column(db.Integer, db.ForeignKey('paper.id'), nullable=False)
    paper = db.relationship('Paper', backref=db.backref('new_papers', lazy=True))
    labeler_id = db.Column(db.Integer, db.ForeignKey('user.id'), nullable=False)
    labeler = db.relationship('User', backref=db.backref('new_papers', lazy=True))
    date_created = db.Column(db.DateTime, default=db.func.current_timestamp())

    def __str__(self):
        return self.title


class Answer(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    paper_id = db.Column(db.Integer, db.ForeignKey('paper.id'), nullable=False)
    paper = db.relationship('Paper', backref=db.backref('answers', lazy=True))
    author_id = db.Column(db.Integer, db.ForeignKey('user.id'), nullable=False)
    author = db.relationship('User', backref=db.backref('answers', lazy=True))
    question_id = db.Column(db.Integer, db.ForeignKey('question.id'), nullable=False)
    question = db.relationship('Question', backref=db.backref('answers', lazy=True))
    answer = db.Column(db.String)
    date_created = db.Column(db.DateTime, default=db.func.current_timestamp())
    updated_on = db.Column(db.DateTime, default=db.func.current_timestamp(), onupdate=db.func.current_timestamp())

    def __str__(self):
        return self.answer

slr_label/slr/__init__.py
from .views import bp

slr_label/slr/views.py
from flask import Blueprint, render_template, redirect, url_for, request, flash
from flask_security import current_user
from slr_label.slr.models import Question, Paper, NewPaper, Answer
from slr_label import db

bp = Blueprint("slr", __name__)


@bp.route("/")
def index():
    """Show all the posts, most recent first."""
    if current_user.is_active and current_user.is_authenticated:
        if current_user.has_role('admin'):
            return redirect(url_for('admin.index', next=request.url))
        else:
            my_papers = current_user.papers
            for my_paper in my_papers:
                answers = my_paper.answers
                my_answers = [answer for answer in answers if answer.author_id == current_user.id]
                if len(my_answers) > 0:
                    my_paper.has_review = 1
                else:
                    my_paper.has_review = 0
            return render_template('slr/index.html', my_papers=my_papers)
    else:
        return redirect(url_for('security.login', next=request.url))


@bp.route("/addPaper")
def add_paper():
    """Show all the posts, most recent first."""
    if current_user.is_active and current_user.is_authenticated:
        papers = Paper.query.all()
        new_papers = NewPaper.query.all()
        all_papers = papers + new_papers
        my_papers = [paper.id for paper in current_user.papers]
        my_papers.sort()
        return render_template('slr/addpaper.html', papers=all_papers, my_papers=my_papers)
    else:
        return redirect(url_for('security.login'))


@bp.route("/addNewPaper", methods=['POST'])
def add_new_paper():
    if request.method == 'POST':
        title = request.form['title']
        authors = request.form['authors']
        venue = request.form['venue']
        doi = request.form['doi']
        from_paper = request.form['from_paper']
        new_paper = NewPaper(title=title, authors=authors, venue=venue, doi=doi, labeler_id=current_user.id, paper_id=from_paper)
        db.session.add(new_paper)
        db.session.commit()
        flash('New paper successfully added!')
    return redirect(url_for('slr.add_paper'))


def get_paper_answers(paper_id):
    paper = Paper.query.filter_by(id=paper_id).first()
    answers = paper.answers  # .filter(Answer.author_id == current_user.id).all()
    my_answers = [answer for answer in answers if answer.author_id == current_user.id]
    answers_dict = {}
    for answer in my_answers:
        answers_dict[str(answer.question_id)] = answer
    questions = Question.query.all()
    for question in questions:
        if str(question.id) in answers_dict:
            question.answer = answers_dict[str(question.id)].answer
        else:
            question.answer = None
    return paper, questions


@bp.route("/reviewPaper", methods=['POST'])
def review_paper():
    if request.method == 'POST':
        paper_id = request.form['paper_id']
        paper, questions = get_paper_answers(paper_id)
        return render_template('slr/reviewpaper.html', paper=paper, questions=questions)
    return redirect(url_for('slr.index'))


@bp.route("/displayReview/<int:paper_id>")
def view_review(paper_id):
    try:
        paper, questions = get_paper_answers(paper_id)
        return render_template('slr/displayreview.html', paper=paper, questions=questions)
    except:
        flash('Error when getting the paper, please check if the paper ID is correct!')
        return redirect(url_for('slr.index'))


@bp.route("/saveReview", methods=['POST'])
def save_review():
    if request.method == 'POST':
        paper_id = request.form['paper_id']
        answers = Answer.query.filter_by(author_id=current_user.id, paper_id=paper_id).all()
        answers_dict = {}
        for answer in answers:
            answers_dict[str(answer.question_id)] = answer
        for k, v in request.form.items():
            if 'question' in k:
                q_id = k.replace('question', '')
                if q_id in answers_dict:
                    answers_dict[q_id].answer = v
                else:
                    new_answer = Answer(answer=v, paper_id=paper_id, author_id=current_user.id, question_id=int(q_id))
                    db.session.add(new_answer)
        db.session.commit()
        flash('Review successfully added/updated!')
    return redirect(url_for('slr.index'))

slr_label/templates/slr/addpaper.html
{% extends 'base.html' %}

{% block header %}
<ul class="nav navbar-nav">
    <li>
        <a href="/">Home</a>
    </li>
    <li class="active">
        <a href="{{ url_for('slr.add_paper') }}">Add Paper</a>
    </li>
</ul>
{% endblock %}

{% block content %}
{% with messages = get_flashed_messages() %}
  {% if messages %}
    {% for message in messages %}
    <div class="alert alert-dismissible alert-success">
      <button type="button" class="close" data-dismiss="alert">&times;</button>
      <strong>{{ message }}</strong>
    </div>
    {% endfor %}
  {% endif %}
{% endwith %}

<p>Add new papers for the systematic literature review here. Only "title" and "from paper" are mandatory.
    The "Title" field is also used for filtering the paper table below. The filtering is applied to all columns,
    which means if you want to filter the paper table with DOI, you can also put DOI value into the "title".</p>

<form method="POST" class="form-horizontal" action="{{ url_for('slr.add_new_paper') }}">
    <div class="form-group">
        <label for="title" class="col-sm-2 control-label">Title (mandatory):</label>
        <div class="col-sm-10"><input type="text" class="form-control" id="title" name="title" onkeyup="paperFilter()" required></div>
    </div>
    <div class="form-group">
        <label for="authors" class="col-sm-2 control-label">Authors:</label>
        <div class="col-sm-10"><input type="text" class="form-control" id="authors" name="authors"></div>
    </div>
    <div class="form-group">
        <label for="venue" class="col-sm-2 control-label">Venue:</label>
        <div class="col-sm-10"><input type="text" class="form-control" id="venue" name="venue"></div>
    </div>
    <div class="form-group">
        <label for="doi" class="col-sm-2 control-label">DOI:</label>
        <div class="col-sm-10"><input type="text" class="form-control" id="doi" name="doi"></div>
    </div>
    <div class="form-group">
        <label for="doi" class="col-sm-2 control-label">From paper (ID):</label>
        <div class="col-sm-10"><select class="form-control" id="from_paper" name="from_paper" required>
            <option value="" selected disabled>Select the paper (ID) from which you can find the new paper</option>
            {% for paper in my_papers %}
            <option value="{{ paper }}">{{ paper }}</option>
            {% endfor %}
        </select></div>
    </div>
    <input type="submit" class="btn btn-primary center-block" value="Add Paper">
</form>


<hr>

<table id="paperTable" class="table table-hover table-light table-striped">
  <thead>
  <tr>
    <th scope="col">Title</th>
      <th scope="col">Authors</th>
    <th scope="col">DOI</th>
  </tr>
  </thead>
    <tbody>
    {% for paper in papers %}
    <tr>
    <td>{{ paper.title }}</td>
    <td>{{ paper.authors }}</td>
    <td>{{ paper.doi }}</td>
    </tr>
    {% endfor %}
    </tbody>
</table>

<script>
function paperFilter() {
  // Declare variables
  var input, filter, table, tr, titleTd, authorTd, doiTd, i, titleValue, authorValue, doiValue, txtValue;
  input = document.getElementById("title");
  filter = input.value.toUpperCase();
  table = document.getElementById("paperTable");
  tr = table.getElementsByTagName("tr");

  // Loop through all table rows, and hide those who don't match the search query
  for (i = 0; i < tr.length; i++) {
    titleTd = tr[i].getElementsByTagName("td")[0];
    authorTd = tr[i].getElementsByTagName("td")[1];
    doiTd = tr[i].getElementsByTagName("td")[2];
    if (titleTd && authorTd && doiTd) {
      titleValue = titleTd.textContent || titleTd.innerText;
      authorValue = authorTd.textContent || authorTd.innerText;
      doiValue = doiTd.textContent || doiTd.innerText;
      txtValue = titleValue+authorValue+doiValue;
      if (txtValue.toUpperCase().indexOf(filter) > -1) {
        tr[i].style.display = "";
      } else {
        tr[i].style.display = "none";
      }
    }
  }
}
</script>
{% endblock %}

slr_label/templates/slr/displayreview.html
{% extends 'base.html' %}

{% block header %}
<ul class="nav navbar-nav">
    <li>
        <a href="/">Home</a>
    </li>
<!--    <li>-->
<!--        <a href="{{ url_for('slr.add_paper') }}">Add Paper</a>-->
<!--    </li>-->
</ul>
{% endblock %}

{% block content %}
<h4>This review is left by <b>{{ current_user.username }}</b> for the following paper.</h4>
<table class="table table-hover">
  <thead>
    <tr>
      <th scope="col">ID</th>
      <th scope="col">Title</th>
      <th scope="col">Authors</th>
      <th scope="col">Venue</th>
    </tr>
  </thead>
  <tbody>
    <tr class="table-dark">
      <th scope="row">{{ paper['id'] }}</th>
      <td>{{ paper['title'] }}</td>
        <td>{{ paper['authors'] }}</td>
        <td>{{ paper['venue'] }}</td>
    </tr>
  </tbody>
</table>

<p>Link: <a href="{{ paper['doi'] }}" target="_blank">{{ paper['doi'] }}</a> </p>

<hr>
    {% for question in questions %}
    <div class="form-group">
      <label for="question{{ question.id }}">{{ question.id }}. {{ question.question }}</label>
      <p>
          {% if question.answer %}
            {{ question.answer }}
          {% endif %}
      </p>
    </div>
    {% endfor %}


<hr>
<button type="button" class="btn btn-success btn-sm center-block" onclick="printPage()">Print this page</button>
<br>
<script>
function printPage() {
  window.print();
}
</script>

{% endblock %}

slr_label/templates/slr/index.html
{% extends 'base.html' %}

{% block header %}
<ul class="nav navbar-nav">
    <li class="active">
        <a href="/">Home</a>
    </li>
<!--    <li>-->
<!--        <a href="{{ url_for('slr.add_paper') }}">Add Paper</a>-->
<!--    </li>-->
</ul>
{% endblock %}

{% block content %}

{% with messages = get_flashed_messages() %}
{% if messages %}
{% for message in messages %}
{% if 'Error' in message%}
<div class="alert alert-dismissible alert-danger">
{% else %}
<div class="alert alert-dismissible alert-success">
    {% endif %}
    <button type="button" class="close" data-dismiss="alert">&times;</button>
    <strong>{{ message }}</strong>
</div>
    {% endfor %}
    {% endif %}
    {% endwith %}

    <h3>My Assigned Papers</h3>
    <p>Click the paper title to enter read-only mode for your review.</p>
    <table class="table table-hover">
        <thead>
        <tr>
            <th scope="col">Paper ID</th>
            <th scope="col">Title</th>
            <th scope="col">Review</th>
        </tr>
        </thead>
        <tbody>
        {% for paper in my_papers %}
        <tr>
            <th scope="row">{{ paper['id'] }}</th>
            <td><a href="{{ url_for('slr.view_review', paper_id=paper['id']) }}">{{ paper['title'] }}</a></td>
            <td>
                <form action="{{ url_for('slr.review_paper') }}" method="post">
                    <input type="hidden" id="paper_id" name="paper_id" value="{{ paper['id'] }}">
                    {% if paper['has_review'] == 1 %}
                    <button type="submit" class="btn btn-success btn-sm">Edit Review</button>
                    {% else %}
                    <button type="submit" class="btn btn-primary btn-sm">Add Review</button>
                    {% endif %}

                </form>
            </td>
        </tr>
        {% endfor %}
        </tbody>
    </table>


    {% endblock %}

slr_label/templates/slr/reviewpaper.html
{% extends 'base.html' %}

{% block header %}
<ul class="nav navbar-nav">
    <li>
        <a href="/">Home</a>
    </li>
<!--    <li>-->
<!--        <a href="{{ url_for('slr.add_paper') }}">Add Paper</a>-->
<!--    </li>-->
</ul>
{% endblock %}

{% block content %}
<h4>Hi {{ current_user.username }}, nou are now reviewing the following paper.</h4>
<table class="table table-hover">
  <thead>
    <tr>
      <th scope="col">ID</th>
      <th scope="col">Title</th>
      <th scope="col">Authors</th>
        <th scope="col">Venue</th>
    </tr>
  </thead>
  <tbody>
    <tr class="table-dark">
      <th scope="row">{{ paper['id'] }}</th>
      <td>{{ paper['title'] }}</td>
        <td>{{ paper['authors'] }}</td>
        <td>{{ paper['venue'] }}</td>
    </tr>
  </tbody>
</table>

<p>Link: <a href="{{ paper['doi'] }}" target="_blank">{{ paper['doi'] }}</a> </p>

<hr>


<form method="POST" action="{{ url_for('slr.save_review') }}">
    {% for question in questions %}
    <div class="form-group">
      <label for="question{{ question.id }}">{{ question.id }}. {{ question.question }}</label>
        {% if question.type == 1 %}
      <textarea class="form-control" id="question{{ question.id }}" name="question{{ question.id }}" rows="3">
      {% if question.answer %}
          {{ question.answer }}
      {% endif %}
      </textarea>
        {% else %}
        <div><select class="form-control" id="question{{ question.id }}" name="question{{ question.id }}" required>
            <option value="" selected disabled>Select the answer</option>
            <option value="Yes">Yes</option>
            <option value="No">No</option>
        </select></div>
        {% endif %}
    </div>
    {% endfor %}
    <input type="hidden" id="paper_id" name="paper_id" value="{{ paper['id'] }}">
    <input type="submit" class="btn btn-primary center-block" value="Submit Review">
</form>

<br>
{% endblock %}